#
dev: nobody

name: Demo Slot

description: Slot demo gacor melatih pola permainan

poster: /assets/images/dafftube.png

avatar: /assets/images/logo_img.png

iklanVideo: https://www.xnxx.com/embedframe/ubuhvlb115b

disqus:

google_analytics: G-MBYBX123VX

url: http://zxbook.online/

baseurl: ""

permalink: /ID-id/:title

version: v1.0.0

kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded

# Google Auth
WA_KEY: 0000000000
SITE_KEY: 6Lf93BUqAAAAAKdOAUYBkBNrQkMz11AYtp-CcYsO
API_KEY: AIzaSyDDYUQN0NsDWYoMSLV4To7JzBjlA0cdHQY
AUTH_DOMAIN: xoilack-maxwin.firebaseapp.com
DATABASE_URL: https://xoilack-maxwin-default-rtdb.firebaseio.com
PROJECT_ID: xoilack-maxwin
STORAGE_BUCKET: xoilack-maxwin.appspot.com
SENDER_ID: 996735481902
APP_ID: 1:996735481902:web:79ab0ffb9a58db1d4e07bf
MEASUREMENT_ID: G-ZNRMZ2QVVZ

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
